---
kind: Pod
apiVersion: v1
metadata:
  name: home-pi-vol01-pod
spec:
  volumes:
    - name: home-pi-pv-storage
      persistentVolumeClaim:
       claimName: home-pi-vol01-claim
  containers:
    - name: home-pi-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-pi-pv-storage
...
---
kind: Pod
apiVersion: v1
metadata:
  name: home-pi-vol02-pod
spec:
  volumes:
    - name: home-pi-pv-storage
      persistentVolumeClaim:
       claimName: home-pi-vol02-claim
  containers:
    - name: home-pi-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-pi-pv-storage
...
---
kind: Pod
apiVersion: v1
metadata:
  name: home-pi-vol03-pod
spec:
  volumes:
    - name: home-pi-pv-storage
      persistentVolumeClaim:
       claimName: home-pi-vol03-claim
  containers:
    - name: home-pi-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-pi-pv-storage
...
---
kind: Pod
apiVersion: v1
metadata:
  name: home-pi-vol04-pod
spec:
  volumes:
    - name: home-pi-pv-storage
      persistentVolumeClaim:
       claimName: home-pi-vol04-claim
  containers:
    - name: home-pi-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-pi-pv-storage
...
---
kind: Pod
apiVersion: v1
metadata:
  name: home-pi-vol05-pod
spec:
  volumes:
    - name: home-pi-pv-storage
      persistentVolumeClaim:
       claimName: home-pi-vol05-claim
  containers:
    - name: home-pi-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-pi-pv-storage
...
---
kind: Pod
apiVersion: v1
metadata:
  name: home-pi-vol06-pod
spec:
  volumes:
    - name: home-pi-pv-storage
      persistentVolumeClaim:
       claimName: home-pi-vol06-claim
  containers:
    - name: home-pi-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-pi-pv-storage
...
---
kind: Pod
apiVersion: v1
metadata:
  name: home-pi-vol07-pod
spec:
  volumes:
    - name: home-pi-pv-storage
      persistentVolumeClaim:
       claimName: home-pi-vol07-claim
  containers:
    - name: home-pi-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: home-pi-pv-storage
...
