---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kubedge-arpscan-ds
  namespace: default
  labels:
    tier: node
    app: arpscan
spec:
  template:
    metadata:
      labels:
        tier: node
        app: arpscan
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: kubedge-arpscan
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/arpscan
        args:
        - enp0s8
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: kubedge
          mountPath: /etc/kubedge
      volumes:
        - name: kubedge
          hostPath:
            path: /etc/kubedge
